rpc_url: "https://api.mainnet-beta.solana.com"
wallets:
  - CbNMHuRaj6DHDzrEn9qDzJC2yo69rb6sntXGpzjhaCs
  - 4oBjRREXU5JAovxjxEhtDjzghfTDUxofhytpQozCquKB
  - GtMp9oemgHN6BPKpztQsMshEpVo5ZgqMhVGcygbiryiP